---
sidebar: sidebar 
permalink: check-clone-integrity.html 
keywords: integrity check, data corruption 
summary: Realice una comprobación de integridad para determinar si los datos de clonado de sandbox están intactos o dañados. 
---
= Compruebe la integridad de los datos en un clon de sandbox
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Realice una comprobación de integridad para determinar si los datos de clonado de sandbox están intactos o dañados.

.Acerca de esta tarea
Cuando crea un clon de sandbox desde una base de datos de origen mientras está ocupado, es posible que los datos del clon no estén sincronizados con la snapshot más reciente de la base de datos de origen. Esta operación comprueba la integridad de todos los objetos del clon del sandbox para determinar si los datos clonados del sandbox son actuales.

.Pasos
. Inicie sesión en el link:https://console.workloads.netapp.com["Consola de Workload Factory"^].
. En el mosaico Bases de datos, seleccione *Ir a Inventario de Bases de Datos*.
. En las bases de datos, seleccione la pestaña *sandboxes*.
. En la pestaña sandboxes, haga clic en el menú de tres puntos del clon del sandbox para comprobar la integridad.
. Selecciona *Ejecutar comprobación de integridad*.
. En el cuadro de diálogo Comprobación de integridad, haga clic en *Comprobación de integridad*.
. Compruebe el estado de la comprobación de integridad en sandboxes o en Supervisión de trabajos.


Si la comprobación de integridad falla, se recomienda no utilizar el clon de sandbox y crear un nuevo clon de sandbox.
