---
sidebar: sidebar 
permalink: connect-clone-cicd.html 
keywords: connect ci/cd pipeline, clone 
summary: Conecte un clon de sandbox a una canalización de CI/CD con código de API REST para mejorar la entrega de software mediante la automatización. 
---
= Conecte un clon de entorno aislado a herramientas CI/CD
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Conecte un clon de sandbox a una canalización de integración continua y entrega continua (CI/CD) con código API REST para mejorar la entrega de software a través de la automatización en NetApp Workload Factory for Databases.

.Acerca de esta tarea
Para entregar una nueva versión del software automáticamente al clon de la base de datos, debe conectarse a una canalización de CI/CD. Utilice el código de API DE REST proporcionado desde esta operación para realizar la conexión.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. Desde el menú Bases de datos, seleccione *Sandboxes*.
. En Sandboxes, seleccione el menú de acciones del clon de sandbox para conectarse a las herramientas de CI/CD.
. Selecciona *Conectar a las herramientas CI/CD*.
. En el cuadro de diálogo CI/CD, copie o descargue el código de API DE REST que necesite para conectarse a las herramientas CI/CD.
. Haga clic en *Cerrar*.

