---
sidebar: sidebar 
permalink: create-postgresql-server.html 
keywords: create, server, PostgreSQL, deploy, host, deploy a database host, database host 
summary: Cree un nuevo servidor SQL PostgreSQL dentro de NetApp Workload Factory para bases de datos. 
---
= Cree un servidor PostgreSQL en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para crear un nuevo servidor PostgreSQL o un host de base de datos en NetApp Workload Factory for Databases se requiere una implementación del sistema de archivos FSx para ONTAP y recursos para Active Directory.



== Acerca de esta tarea

Antes de crear un servidor PostgreSQL desde Workload Factory, obtenga información sobre los tipos de implementación de almacenamiento disponibles para la configuración del host de la base de datos, los modos de operación de Workload Factory y los requisitos para completar esta operación.

.FSX para puestas en marcha del sistema de archivos ONTAP
Para crear un nuevo servidor PostgreSQL, se requiere un sistema de archivos FSx para ONTAP como back-end de almacenamiento. Puede utilizar un sistema de archivos FSX for ONTAP existente o crear un nuevo sistema de archivos. Si selecciona un sistema de archivos FSx para ONTAP existente como back-end de almacenamiento de servidor de bases de datos, creamos una nueva máquina virtual de almacenamiento para las cargas de trabajo de PostgreSQL.

+ FSx para sistemas de archivos ONTAP tiene dos modelos de implementación de servidor PostgreSQL: _Alta disponibilidad (HA)_ o _instancia única_.  Se crean diferentes recursos para el sistema de archivos FSx para ONTAP según el modelo de implementación de FSx para ONTAP que seleccione.

* *Despliegue de alta disponibilidad*: Se implementa un sistema de archivos FSX para NetApp ONTAP de varias zonas de disponibilidad cuando se selecciona un nuevo sistema de archivos FSX para ONTAP para la implementación de alta disponibilidad. Se crean volúmenes y LUN independientes para archivos de datos, registros y tempdb para una implementación de HA. Se crean un volumen y LUN adicionales para el disco de quórum o de testigo para el clúster de Windows. La implementación de HA configura la replicación de streaming entre los servidores PostgreSQL primarios y secundarios.
* *Implementación de instancia única*: Se crea un sistema de archivos FSX de zona de disponibilidad única para ONTAP cuando se crea un nuevo servidor PostgreSQL. Además, se crean volúmenes y LUN independientes para archivos de datos, registros y tempdb.




== Antes de empezar

Debes tener link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["otorgar permisos de creación de host de base de datos"^] en su cuenta de AWS para crear un nuevo host de base de datos en Workload Factory.



== Crear un servidor PostgreSQL

Puede utilizar los modos de implementación _Quick create_ o _Advanced create_ para completar esta tarea en la fábrica de cargas de trabajo con permisos de modo _automate_. También puede usar las siguientes herramientas disponibles en CodeBox: API REST, CLI de AWS, AWS CloudFormation y Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Aprende a usar CodeBox para la automatización"^].


NOTE: Al usar Terraform de CodeBox, el código que copie o descargue oculta `fsxadmin` y `vsadmin` las contraseñas. Deberá volver a introducir las contraseñas cuando ejecute el código. Deberá incluir los siguientes permisos para la cuenta de usuario además de los permisos del modo _Automate_: `iam:TagRole` Y `iam:TagInstanceProfile`. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#use-terraform-from-codebox["Aprende a usar Terraform de CodeBox"^].

[role="tabbed-block"]
====
.Creación rápida
--

NOTE: En _Quick create_, HA es el modelo de implementación predeterminado, Windows 2016 es la versión predeterminada de Windows y SQL 2019 Standard Edition es la versión predeterminada de SQL.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Implementar host* y luego seleccione *Servidor PostgreSQL* en el menú.
. Seleccione *Quick create*.
. En *Zona de aterrizaje*, proporcione lo siguiente:
+
.. *Credenciales de AWS*: Seleccione las credenciales de AWS con permisos automatizados para implementar el nuevo host de base de datos.
+
Las credenciales de AWS con permisos de _lectura/escritura_ permiten que Workload Factory implemente y administre el nuevo host de base de datos desde su cuenta de AWS dentro de Workload Factory.

+
Las credenciales de AWS con permisos de _solo lectura_ permiten que la fábrica de carga de trabajo genere una plantilla de CloudFormation para que usted la use en la consola de AWS CloudFormation.

+
Si no tiene las credenciales de AWS asociadas en la fábrica de cargas de trabajo y desea crear el nuevo servidor en la fábrica de cargas de trabajo, siga la opción *1* para ir a la página Credenciales. Agregue manualmente las credenciales y los permisos necesarios para el modo _lectura/escritura_ para las cargas de trabajo de la base de datos.

+
Si desea completar el formulario Crear nuevo servidor en la fábrica de cargas de trabajo para poder descargar una plantilla de archivo YAML completa para su implementación en AWS CloudFormation, siga *Opción 2* para asegurarse de que tiene los permisos necesarios para crear el nuevo servidor en AWS CloudFormation. Agregue manualmente las credenciales y los permisos necesarios para el modo _solo lectura_ para las cargas de trabajo de la base de datos.

+
Opcionalmente, puede descargar una plantilla de archivo YAML parcialmente completada desde CodeBox para crear la pila fuera de la fábrica de cargas de trabajo sin credenciales ni permisos. Seleccione *CloudFormation* en el menú desplegable del CodeBox para descargar el archivo YAML.

.. *Región y VPC*: Seleccione una región y una red de VPC.
+
Asegúrese de que los grupos de seguridad para un extremo de interfaz existente permiten el acceso al protocolo HTTPS (443) a las subredes seleccionadas.

+
Extremos de la interfaz de servicio de AWS (SQS, FSx, EC2, CloudWatch, CloudFormation, SSM) y el punto final de la puerta de enlace S3 se crean durante el despliegue si no se encuentra.

+
Los atributos DNS de VPC `EnableDnsSupport` y `EnableDnsHostnames` se modifican para activar la resolución de direcciones de punto final si aún no están establecidos en `true`.

.. *Zonas de disponibilidad*: Seleccione zonas de disponibilidad y subredes.
+

NOTE: Las implementaciones de HA solo se admiten en configuraciones FSx para ONTAP de varias zonas de disponibilidad (MAZ).

+
Las subredes no deben compartir la misma tabla de rutas para alta disponibilidad.

+
... En el campo *Configuración de clúster - Nodo 1*, seleccione la zona de disponibilidad principal para la configuración de MAZ FSX para ONTAP en el menú desplegable *Zona de disponibilidad* y una subred de la zona de disponibilidad principal desde el menú desplegable *Subred*.
... En el campo *Configuración de clúster - Nodo 2*, seleccione la zona de disponibilidad secundaria para la configuración de MAZ FSX para ONTAP en el menú desplegable *Zona de disponibilidad* y una subred de la zona de disponibilidad secundaria desde el menú desplegable *Subred*.




. En *Configuración de la aplicación*, introduzca un nombre de usuario y una contraseña para *Credenciales de la base de datos*.
. En *Conectividad*, selecciona un par de claves para conectarte de forma segura a tu instancia.
. En *Configuración de infraestructura*, proporcione lo siguiente:
+
.. *FSX para el sistema ONTAP*: Crea un nuevo sistema de archivos FSX para ONTAP o usa un sistema de archivos FSX para ONTAP existente.
+
... * Crear nuevo FSX para ONTAP*: Introduzca el nombre de usuario y la contraseña.
+
Un nuevo sistema de archivos FSX para ONTAP puede agregar 30 minutos o más de tiempo de instalación.

... *Seleccione un FSX para ONTAP*: Seleccione FSX para el nombre de ONTAP en el menú desplegable, e introduzca un nombre de usuario y una contraseña para el sistema de archivos.
+
Para los sistemas de archivos FSx para ONTAP existentes, asegúrate de lo siguiente:

+
**** El grupo de enrutamiento conectado a FSx para ONTAP permite que las rutas a las subredes se utilicen para la implementación.
**** El grupo de seguridad permite el tráfico de las subredes utilizadas para la puesta en marcha, específicamente los puertos TCP HTTPS (443) e iSCSI (3260).




.. *Tamaño de la unidad de datos*: Ingrese la capacidad de la unidad de datos y seleccione la unidad de capacidad.


. Resumen:
+
.. *Vista previa predeterminada*: Revise las configuraciones predeterminadas establecidas por Quick Create.
.. *Costo estimado*: Proporciona una estimación de los cargos en los que podría incurrir si implementa los recursos mostrados.


. Haga clic en *Crear*.
+
Como alternativa, si desea cambiar cualquiera de estos valores por defecto ahora, cree el servidor de base de datos con Advanced CREATE.

+
También puede seleccionar *Guardar configuración* para implementar el host más tarde.



--
.Creación avanzada
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Implementar host* y luego seleccione *Servidor PostgreSQL* en el menú.
. Selecciona *Creación avanzada*.
. En *Modelo de implementación*, selecciona *Instancia independiente* o *Alta disponibilidad (HA)*.
. En *Zona de aterrizaje*, proporcione lo siguiente:
+
.. *Credenciales de AWS*: Seleccione las credenciales de AWS con permisos automatizados para implementar el nuevo host de base de datos.
+
Las credenciales de AWS con permisos _Automate_ permiten que la fábrica de cargas de trabajo implemente y administre el nuevo host de base de datos desde su cuenta de AWS dentro de la fábrica de cargas de trabajo.

+
Las credenciales de AWS con permisos de _solo lectura_ permiten que la fábrica de carga de trabajo genere una plantilla de CloudFormation para que usted la use en la consola de AWS CloudFormation.

+
Si no tiene las credenciales de AWS asociadas en la fábrica de cargas de trabajo y desea crear el nuevo servidor en la fábrica de cargas de trabajo, siga la opción *1* para ir a la página Credenciales. Agregue manualmente las credenciales y los permisos necesarios para el modo _lectura/escritura_ para las cargas de trabajo de la base de datos.

+
Si desea completar el formulario Crear nuevo servidor en la fábrica de cargas de trabajo para poder descargar una plantilla de archivo YAML completa para su implementación en AWS CloudFormation, siga *Opción 2* para asegurarse de que tiene los permisos necesarios para crear el nuevo servidor en AWS CloudFormation. Agregue manualmente las credenciales y los permisos necesarios para el modo _solo lectura_ para las cargas de trabajo de la base de datos.

+
Opcionalmente, puede descargar una plantilla de archivo YAML parcialmente completada desde CodeBox para crear la pila fuera de la fábrica de cargas de trabajo sin credenciales ni permisos. Seleccione *CloudFormation* en el menú desplegable del CodeBox para descargar el archivo YAML.

.. *Región y VPC*: Seleccione una región y una red de VPC.
+
Asegúrese de que los grupos de seguridad para un extremo de interfaz existente permiten el acceso al protocolo HTTPS (443) a las subredes seleccionadas.

+
Extremos de la interfaz del servicio de AWS (SQS, FSx, EC2, CloudWatch, formación de la nube, SSM) y el punto final de la puerta de enlace S3 se crean durante el despliegue si no se encuentra.

+
Los atributos DNS de VPC `EnableDnsSupport` y `EnableDnsHostnames` se modifican para activar la resolución de la dirección de punto final si no se ha establecido ya en `true`.

.. *Zonas de disponibilidad*: Seleccione zonas de disponibilidad y subredes.
+
*Para implementaciones de instancia única*

+
En el campo *Configuración del clúster - Nodo 1*, seleccione una zona de disponibilidad en el menú desplegable *Zona de disponibilidad* y una subred en el menú desplegable *Subred*.

+
*Para implementaciones de alta disponibilidad*

+
... En el campo *Configuración de clúster - Nodo 1*, seleccione la zona de disponibilidad principal para la configuración de MAZ FSX para ONTAP en el menú desplegable *Zona de disponibilidad* y una subred de la zona de disponibilidad principal desde el menú desplegable *Subred*.
... En el campo *Configuración de clúster - Nodo 2*, seleccione la zona de disponibilidad secundaria para la configuración de MAZ FSX para ONTAP en el menú desplegable *Zona de disponibilidad* y una subred de la zona de disponibilidad secundaria desde el menú desplegable *Subred*.


.. *Grupo de seguridad*: Seleccione un grupo de seguridad existente o cree un nuevo grupo de seguridad.
+
Dos grupos de seguridad se conectan a los nodos SQL (instancias EC2) durante el despliegue del nuevo servidor.

+
... Se crea un grupo de seguridad de carga de trabajo para permitir los puertos y protocolos necesarios para PostgreSQL.
... Para un nuevo sistema de archivos FSx for ONTAP, se crea un nuevo grupo de seguridad y se conecta al nodo SQL. Para un sistema de archivos FSX for ONTAP existente, el grupo de seguridad asociado con él se agrega automáticamente al nodo PostgreSQL que permite la comunicación con el sistema de archivos.




. En *Configuración de la aplicación*, proporcione lo siguiente:
+
.. Seleccione el *Sistema operativo* en el menú desplegable.
.. Seleccione la *versión PostgreSQL* del menú desplegable.
.. *Nombre del servidor de base de datos*: Introduzca el nombre del cluster de base de datos.
.. *Credenciales de la base de datos*: Introduzca un nombre de usuario y una contraseña para una nueva cuenta de servicio o utilice las credenciales de la cuenta de servicio existentes en Active Directory.


. En *Conectividad*, selecciona un par de claves para conectarte de forma segura a tu instancia.
. En *Configuración de infraestructura*, proporcione lo siguiente:
+
.. *Tipo de instancia de DB*: Seleccione el tipo de instancia de base de datos en el menú desplegable.
.. *FSX para el sistema ONTAP*: Crea un nuevo sistema de archivos FSX para ONTAP o usa un sistema de archivos FSX para ONTAP existente.
+
... * Crear nuevo FSX para ONTAP*: Introduzca el nombre de usuario y la contraseña.
+
Un nuevo sistema de archivos FSX para ONTAP puede agregar 30 minutos o más de tiempo de instalación.

... *Seleccione un FSX para ONTAP*: Seleccione FSX para el nombre de ONTAP en el menú desplegable, e introduzca un nombre de usuario y una contraseña para el sistema de archivos.
+
Para los sistemas de archivos FSx para ONTAP existentes, asegúrate de lo siguiente:

+
**** El grupo de enrutamiento conectado a FSx para ONTAP permite que las rutas a las subredes se utilicen para la implementación.
**** El grupo de seguridad permite el tráfico de las subredes utilizadas para la puesta en marcha, específicamente los puertos TCP HTTPS (443) e iSCSI (3260).




.. *Política de instantáneas*: Habilitado por defecto. Las copias Snapshot se realizan diariamente y tienen un período de retención de 7 días.
+
Las snapshots se asignan a volúmenes creados para las cargas de trabajo PostgreSQL.

.. *Tamaño de la unidad de datos*: Ingrese la capacidad de la unidad de datos y seleccione la unidad de capacidad.
.. *IOPS provisionadas*: Selecciona *Automático* o *Provisioned por el usuario*. Si selecciona *Provisioned por el usuario*, introduzca el valor de IOPS.
.. *Capacidad de rendimiento*: Seleccione la capacidad de rendimiento en el menú desplegable.
+
En algunas regiones, puede seleccionar una capacidad de rendimiento de 4 Gbps. Para aprovisionar 4 Gbps de capacidad de rendimiento, su sistema de archivos FSx para ONTAP debe configurarse con un mínimo de 5.120 GiB de capacidad de almacenamiento SSD y 160.000 IOPS SSD.

.. *Cifrado*: Selecciona una clave de tu cuenta o una clave de otra cuenta. Debe introducir la clave de cifrado ARN desde otra cuenta.
+
Las claves de cifrado personalizadas de FSx para ONTAP no se incluyen en la aplicación del servicio. Seleccione una clave de cifrado FSX adecuada. Las claves de cifrado no FSX provocarán un error en la creación del servidor.

+
Las claves gestionadas por AWS se filtran en función de la aplicabilidad del servicio.

.. *Etiquetas*: Opcionalmente, puedes añadir hasta 40 etiquetas.
.. *Servicio de Notificación Simple*: Opcionalmente, puede habilitar el Servicio de Notificación Simple (SNS) para esta configuración seleccionando un tema de SNS para Microsoft SQL Server en el menú desplegable.
+
... Active Simple Notification Service.
... Seleccione un ARN en el menú desplegable.


.. *Monitoreo de CloudWatch*: Opcionalmente, puede habilitar el monitoreo de CloudWatch.
+
Recomendamos habilitar CloudWatch para la depuración en caso de fallo. Los eventos que aparecen en la consola de AWS CloudFormation son de alto nivel y no especifican la causa raíz. Todos los registros detallados se guardan en `C:\cfn\logs` la carpeta de las instancias de EC2.

+
En CloudWatch, se crea un grupo de registros con el nombre de la pila. En el grupo de registros aparece un flujo de registro para cada nodo de validación y nodo SQL. CloudWatch muestra el progreso del script y proporciona información para ayudarle a comprender si falla la implementación y cuándo.

.. *Retroceder recursos*: Esta característica no es compatible actualmente.


. Resumen
+
.. *Costo estimado*: Proporciona una estimación de los cargos en los que podría incurrir si implementa los recursos mostrados.


. Haga clic en *Crear* para implementar el nuevo host de base de datos.
+
También puede guardar la configuración.



--
====
.El futuro
Puede configurar manualmente usuarios, acceso remoto y bases de datos en el servidor PostgreSQL desplegado.
