---
sidebar: sidebar 
permalink: create-database.html 
keywords: create, database, creation, Microsoft SQL 
summary: Cree una base de datos de Microsoft SQL con NetApp Workload Factory for Databases. 
---
= Cree una base de datos de Microsoft SQL en NetApp Workload Factory para bases de datos
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La creación de una nueva base de datos de Microsoft SQL le permite administrar el recurso dentro de NetApp Workload Factory for Databases.

.Acerca de esta tarea
Tras la creación de la base de datos, se crean dos nuevos volúmenes en el sistema de archivos FSx para ONTAP que consta de LUN independientes para alojar datos y archivos de registro de la base de datos. Los archivos de base de datos de la nueva base de datos están aprovisionados mediante thin provisioning y consumen sólo unos MB del tamaño total asignado a la nueva base de datos.

Si desea segregar el almacenamiento para la base de datos, puede hacerlo mediante un _punto de montaje virtual_. El punto de montaje virtual permite consolidar bases de datos en unas pocas unidades comunes en el host.

La creación de una base de datos en Workload Factory requiere permisos de _visualización, planificación y análisis_. Como alternativa, puede copiar o descargar una plantilla de código parcialmente completada para completar la operación fuera de la fábrica de cargas de trabajo. link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Obtenga información sobre los permisos de Workload Factory"^] para decidir qué modo desea utilizar.


NOTE: Los servidores Microsoft SQL Server que utilizan el protocolo SMB no admiten la creación de bases de datos.

.Antes de empezar
Asegúrese de completar los siguientes requisitos previos antes de crear una nueva base de datos.

* *Credenciales y permisos*: Debe tener link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Credenciales de la cuenta de AWS y permisos de _visualización, planificación y análisis_"^] para crear una nueva base de datos en Workload Factory.
+
Como alternativa, puede utilizar CodeBox para copiar una plantilla de forma que pueda implementar una base de datos fuera de la fábrica de cargas de trabajo mediante la API REST. link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Obtenga más información sobre la automatización de CodeBox"^].

* *Host de Windows*: debe tener suficientes letras de unidad disponibles en Microsoft SQL Server para crear nuevas unidades para la nueva base de datos si utiliza el modo _Creación rápida_.
* *Microsoft SQL Server*: debe tener un Microsoft SQL Server administrado en la fábrica de carga de trabajo para que las bases de datos alojen la nueva base de datos.
* *Administrador de sistemas de AWS*: garantizar que `NT Authority\SYSTEM` El privilegio de usuario se habilita en el host de Microsoft SQL a través de AWS Systems Manager.




== Cree una base de datos

Puede utilizar los modos de implementación _Creación rápida_ o _Creación avanzada_ para completar esta tarea en Workload Factory.

[role="tabbed-block"]
====
.Creación rápida
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. Desde el menú Bases de datos, seleccione *Inventario*.
. En el Inventario, seleccione *Microsoft SQL Server* como tipo de motor de base de datos.
. Seleccione un servidor de base de datos con una instancia de servidor SQL administrado para crear la base de datos.
. Haga clic en el menú de acciones de la instancia administrada y luego seleccione *Crear base de datos de usuario*.
. En la página Crear base de datos de usuario, en Información de base de datos, proporcione lo siguiente:
+
.. *Nombre de la base de datos*: Introduzca el nombre de la base de datos.
.. *Collation*: Seleccione una clasificación para la base de datos. Se ha seleccionado la intercalación predeterminada SQL_Latin1_General_CP1_CI_AS en Microsoft SQL Server.


. En Configuración de archivo, proporcione lo siguiente:
+
.. *Modo de configuración de archivo*: Selecciona *Quick create*.
.. *Nombres de archivo y ruta*:
+
*** *Nombre del archivo de datos*: Introduzca el nombre del archivo de datos.
*** *Nombre del archivo de registro*: Introduzca el nombre del archivo de registro.


.. * Tamaños de archivo*: Introduzca el tamaño de los datos y el tamaño del registro para la base de datos.


. Haga clic en *Crear*.
+
Alternativamente, si desea cambiar cualquiera de estos ajustes predeterminados ahora, cambie el *Modo de configuración de archivo* a *Creación avanzada*.



--
.Creación avanzada
--
.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. Desde el menú Bases de datos, seleccione *Inventario*.
. En el Inventario, seleccione *Microsoft SQL Server* como tipo de motor de base de datos.
. Seleccione un servidor de base de datos con una instancia de servidor SQL administrado para crear la base de datos.
. Haga clic en el menú de acciones de la instancia administrada y luego seleccione *Crear base de datos de usuario*.
. Seleccione *Crear base de datos de usuario*.
. En la página Crear base de datos de usuario, en Información de base de datos, proporcione lo siguiente:
+
.. *Nombre de la base de datos*: Introduzca el nombre de la base de datos.
.. *Collation*: Seleccione la intercalación para la base de datos. Se ha seleccionado la intercalación predeterminada SQL_Latin1_General_CP1_CI_AS en Microsoft SQL Server.


. En Configuración de archivo, proporcione lo siguiente:
+
.. *Modo de configuración de archivo*: Selecciona *Creación avanzada*.
.. *Nombres de archivo y ruta*:
+
... *Archivo de datos*: Seleccione una letra de unidad e introduzca el nombre del archivo de datos.
+
Opcionalmente, haga clic en la casilla de *Punto de montaje virtual*.

... *Archivo de registro*: Seleccione una letra de unidad e introduzca el nombre del archivo de registro.
+
Opcionalmente, haga clic en la casilla de *Punto de montaje virtual*.



.. * Tamaños de archivo*: Introduzca el tamaño de los datos y el tamaño del registro para la base de datos.


. Haga clic en *Crear*.


--
====
Si creó el host de la base de datos, puede comprobar el progreso del trabajo en la pestaña *Supervisión de trabajos*.
