---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: NetApp Workload Factory for Databases es un servicio de implementación y mantenimiento de bases de datos de extremo a extremo con mejores prácticas integradas para optimización, clonación fina automática y capacidades de monitoreo y resolución. 
---
= Obtenga más información sobre NetApp Workload Factory para bases de datos
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases es un servicio de implementación y mantenimiento de bases de datos de extremo a extremo con mejores prácticas integradas para optimización, clonación fina automática y capacidades de monitoreo y resolución.



== ¿Qué es NetApp Workload Factory para bases de datos?

NetApp Workload Factory for Databases detecta, evalúa, planifica, aprovisiona y mueve datos de Microsoft SQL Server a implementaciones de Amazon FSx for NetApp ONTAP (FSx for ONTAP) optimizadas para cumplir con sus expectativas de rendimiento y costos y, al mismo tiempo, adherirse a las mejores prácticas de la industria.  A lo largo del ciclo de vida, NetApp Workload Factory for Databases ofrece optimización y gestión continuas de bases de datos en FSx para ONTAP.

Para obtener más información sobre Workload Factory, consultelink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Descripción general de Workload Factory"^] .



== Beneficios de Workload Factory para bases de datos autogestionadas

Workload Factory ofrece las siguientes prácticas recomendadas y automatización beneficiosas para bases de datos autoadministradas.



=== Mejores prácticas

* Conocimiento integrado de la nube de AWS, servidores de Microsoft Windows y SQL, y NetApp ONTAP para puestas en marcha de SQL Server en instancias EC2.
* Coste total de propiedad Implementación optimizada.
* Automatización de puesta en marcha integral que sigue las prácticas recomendadas de AWS, Microsoft y ONTAP.
* El modo de implementación _Creación rápida_ le ayuda a evitar posibles problemas con la configuración manual.




=== Automatización con Workload Factory Codebox

Workload Factory introduce automatización incorporada con _Codebox_.  Codebox ofrece los siguientes beneficios de automatización:

* *Generación de fragmentos de código*: Los fragmentos de infraestructura como código (IAC) se generan durante la creación de recursos, lo que permite una integración perfecta con los flujos de trabajo de orquestación existentes.
* *Copiloto de infraestructura como código*: Codebox es un copiloto de infraestructura como código (IaC) que ayuda a los desarrolladores y DevOps a generar código para ejecutar cualquier operación compatible con Workload Factory.
* *Visor de código y catálogo de automatización*: El CodeBox proporciona un visor de código para un análisis rápido de la automatización y un catálogo de automatización para una rápida reutilización futura.




=== Características de Workload Factory para bases de datos

Workload Factory for Databases ofrece las siguientes características:

* * Implementaciones sencillas y rápidas*: Simplifique y optimice su experiencia de aprovisionamiento seleccionando respuestas a preguntas de especificación y eliminando el tiempo que normalmente se requiere para investigar cómo aprovisionar y configurar su Microsoft SQL Server en AWS.
* *Orquestación automatizada*: disponible a través de la consola Workload Factory con los modos de implementación de creación _Rápido_ y _Avanzado_, el Chatbot y AWS CloudFormation a través de Codebox.
* * Funciones incorporadas*: Utilice las mejores prácticas de NetApp, Microsoft y Amazon y selecciones de recursos de AWS integradas en la configuración de implementación.
* * Estimación de costes*: Evalúe el ahorro de costes potencial con la calculadora de ahorros que calcula y detalla el almacenamiento, la computación, las licencias de SQL, las instantáneas y los costos detallados de las implementaciones existentes de Microsoft SQL Server con Elastic Block Store y FSx para el servidor de archivos de Windows en comparación con FSx para ONTAP.
* *Plantillas de automatización reutilizables*: cree, reutilice y personalice plantillas de CloudFormation desde Workload Factory Codebox para futuras implementaciones de Microsoft SQL Server en múltiples entornos.
* * Descubrimiento y aprovisionamiento de recursos de AWS*: Detecte automáticamente Microsoft SQL Server en FSx para ONTAP, FSx para servidores de archivos de Windows y Elastic Block Store desplegados desde su cuenta de AWS. El Inventario de Bases de Datos sirve como punto de partida para explorar oportunidades de ahorro de costes para servidores en otros sistemas de almacenamiento de AWS o una herramienta de gestión para instancias y servidores basados en FSx para ONTAP.
* *Creación de Sandbox*: Cree un entorno de base de datos aislado y bajo demanda que se pueda utilizar para pruebas, integración, diagnóstico y capacitación, sin afectar a los datos de producción.
* * Creación de bases de datos*: Cree una base de datos de usuario para sus servidores Microsoft SQL Server existentes con los modos _Quick_ o _Advanced_ para configurar la clasificación de la base de datos, los nombres de los archivos y los tamaños. Se incluye la configuración del almacenamiento.
* *Monitoreo de trabajos*: Monitoree y rastree el progreso de la ejecución de trabajos de la base de datos y diagnostique y solucione problemas en caso de que ocurra algún fallo.
* *Optimización continua*: Analiza continuamente su estado de Microsoft SQL Server sin conexión, proporcionándole un informe completo de ideas, oportunidades y recomendaciones para ayudarle a alcanzar la excelencia operativa.




== Beneficios de Amazon FSx para ONTAP para las bases de datos autogestionadas

* * Durabilidad, disponibilidad y fiabilidad*: FSX for ONTAP ofrece múltiples características que mejoran la durabilidad y disponibilidad de las bases de datos autogestionadas alojadas en FSx for ONTAP, como la alta disponibilidad compatible con implementaciones de zonas de disponibilidad únicas y múltiples, instantáneas para aplicaciones, recuperación de desastres mejorada mediante replicación y copias de seguridad eficientes.
* *Rendimiento y escalabilidad*: FSX para ONTAP ofrece optimización del rendimiento con alto rendimiento, baja latencia, conexiones de red de alta velocidad y escalabilidad con múltiples sistemas de archivos para escalar el rendimiento agregado requerido para una carga de trabajo.
* * Gestión de datos y eficiencia*: FSX para ONTAP ofrece múltiples funciones que mejoran la gestión y la eficiencia de los datos, como clones ligeros con gestión eficiente del espacio, thin provisioning, compresión y deduplicación y organización en niveles de los datos a los que se accede con poca frecuencia en el pool de capacidad.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["Obtenga más información sobre FSx para ONTAP para Workload Factory"^] .



=== Modos operativos en Workload Factory

Tres modos operativos diferentes - _básico_, _solo lectura_ y _lectura/escritura_ - ofrecen opciones flexibles para la implementación dentro y fuera de Workload Factory. Obtenga valor inmediato en modo de confianza cero en modo _básico_ con fragmentos de código para usar fuera de Workload Factory. Obtenga valor incremental con confianza incremental en los modos _solo lectura_ y _lectura/escritura_.

Obtenga más información sobre link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["modos operativos en Workload Factory"^] .



== Herramientas para utilizar NetApp Workload Factory

Puede utilizar NetApp Workload Factory con las siguientes herramientas:

* *Consola Workload Factory*: La consola Workload Factory proporciona una vista visual y holística de sus aplicaciones y proyectos.
* *Consola NetApp *: La consola NetApp proporciona una experiencia de interfaz híbrida para que pueda utilizar Workload Factory junto con otros servicios de datos de NetApp .
* *Pregúntame*: utiliza el asistente de IA Pregúntame para hacer preguntas y obtener más información sobre Workload Factory sin salir de la consola de Workload Factory. Accede a Pregúntame desde el menú de ayuda de Workload Factory.
* *CloudShell CLI*: Workload Factory incluye una CLI de CloudShell para administrar y operar entornos de AWS y NetApp en todas las cuentas desde una única CLI basada en navegador. Acceda a CloudShell desde la barra superior de la consola de Workload Factory.
* *API REST*: utilice las API REST de Workload Factory para implementar y administrar sus sistemas de archivos FSx para ONTAP y otros recursos de AWS.
* *CloudFormation*: use el código de AWS CloudFormation para realizar las acciones que definió en la consola de Workload Factory para modelar, aprovisionar y administrar recursos de AWS y de terceros desde la pila de CloudFormation en su cuenta de AWS.
* *Proveedor de Terraform NetApp Workload Factory*: utilice Terraform para crear y administrar flujos de trabajo de infraestructura generados en la consola de Workload Factory.




== Configuraciones admitidas

Workload Factory admite los siguientes motores de bases de datos, versiones, sistemas operativos y modelos de implementación según las mejores prácticas de AWS, NetApp ONTAP, Microsoft SQL Server, Oracle y PostgreSQL.

[cols="1,1,1,1"]
|===
| Motor | Versión | Sistema operativo | Modelo de implementación 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI, instancia única 


| Microsoft SQL Server | Servidor SQL 2017 | Cualquier | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | Cualquier | FCI, instancia única 


| Microsoft SQL Server | SQL Server 2016, 2019, 2022 | Cualquier | Grupos de disponibilidad siempre activos 


| Oráculo | 19c | RHEL, SuSe Linux | Independiente (inquilino único o múltiple) 


| Oráculo | 21c | RHEL, SuSe Linux | Independiente (inquilino único o múltiple) 


| Oráculo | 19c | RHEL, SuSe Linux | Independiente (inquilino único o múltiple) 


| Oráculo | 21c | RHEL, SuSe Linux | Independiente (inquilino único o múltiple) 


| Oráculo | 19c | RHEL, SuSe Linux | Independiente con ASM (inquilino único o múltiple) 


| Oráculo | 21c | RHEL, SuSe Linux | Independiente con ASM (inquilino único o múltiple) 


| Oráculo | 19c | RHEL, SuSe Linux | Guardia de datos 


| Oráculo | 21c | RHEL, SuSe Linux | Guardia de datos 


| PostgreSQL | PostgreSQL 15 | AMI de Amazon Linux 2023 | HA, instancia independiente 


| PostgreSQL | PostgreSQL 16 | AMI de Amazon Linux 2023 | HA, instancia independiente 
|===


== Servicios de AWS integrados

Las bases de datos incluyen los siguientes servicios integrados de AWS:

* Formación CloudFormation
* Servicio de notificación simple
* CloudWatch
* Administrador de sistemas
* Administrador de secretos




== Regiones

Las bases de datos están soportadas en todas las regiones comerciales en las que se soporta FSX para ONTAP. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Consulte las regiones de Amazon admitidas."^]

No se admiten las siguientes regiones de AWS:

* Regiones de China
* Regiones GovCloud (EE. UU.
* Cloud secreto
* Cloud secreto superior




== Obtener ayuda

Amazon FSX para ONTAP de NetApp es una solución de primera parte de AWS. Para preguntas o problemas de soporte técnico asociados con tu ONTAP sistema de archivos, infraestructura o cualquier solución que use este servicio, usa el Centro de soporte de tu consola de administración de AWS para abrir un caso de soporte con AWS. Seleccione el servicio "FSX for ONTAP" y la categoría adecuada. Proporcione la información restante necesaria para crear su caso de soporte de AWS.

Para preguntas generales sobre Workload Factory o las aplicaciones y servicios de Workload Factory, consultelink:get-help.html["Obtenga ayuda para NetApp Workload Factory for Databases"] .
