---
sidebar: sidebar 
permalink: manage-server.html 
keywords: Microsoft SQL Server instance, server instance, manage host, view host, database host, database instance, manage, unmanage 
summary: Gestione instancias de Microsoft SQL Server en la fábrica de cargas de trabajo de BlueXP  para bases de datos. 
---
= Gestione instancias de Microsoft SQL Server en la fábrica de cargas de trabajo de BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Gestione instancias de Microsoft SQL Server para supervisar el estado de la instancia y la base de datos, la utilización de recursos, la protección y el rendimiento del almacenamiento en el fábrica de cargas de trabajo de BlueXP  para bases de datos.

Las bases de datos solo pueden gestionar instancias de Microsoft SQL Server con el almacenamiento del sistema de archivos FSx para ONTAP.



== Gestión de instancias de Microsoft SQL Server

La gestión de instancias de Microsoft SQL Server incluye las siguientes tareas:

* Gestione una instancia de host
* Ver una instancia gestionada
* Ver bases de datos
* Anular la gestión de una instancia de host


Para completar cualquiera de estas tareas, debe link:detect-host.html["detectar una o más instancias de host"^].



== Gestione una instancia de host

Gestionar instancias de Microsoft SQL Server detectadas o no gestionadas para un host.

Para administrar una instancia de host en una red privada sin conectividad externa, los siguientes puntos finales deben estar disponibles en la VPC con asociación a las subredes donde están presentes los servidores SQL. Asegúrese de que los extremos de interfaz permiten el puerto 443 en el grupo de seguridad conectado.

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`


.Antes de empezar
Complete los siguientes requisitos previos antes de comenzar:

* Debe haber detectado una instancia en el host que está disponible para la gestión.
* Se necesita PowerShell7 para gestionar la instancia de la base de datos. Instale PowerShell7 manualmente consultando link:https://learn.microsoft.com/en-us/powershell/scripting/developer/module/installing-a-powershell-module?view=powershell-7.4["Documentación de Microsoft PowerShell para Windows"^].
* Todas las operaciones de gestión las ejecuta el agente de AWS System Manager mediante `NT Authority\SYSTEM` privilegios de usuario. Proporcione los siguientes permisos para `NT Authority\SYSTEM` el usuario en el servidor de bases de datos:
+
** `“ALTER SETTINGS”`
** `“CONTROL SERVER”`
** `“ALTER ANY DATABASE”`
** `“VIEW ANY DEFINITION”`
** `“CONNECT ANY DATABASE”`
** `“CREATE ANY DATABASE”`




.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. En Bases de datos, seleccione la pestaña *Inventario*.
. Haga clic en *Administrar* en la fila del host para administrar.
. Seleccione una o más instancias de host para gestionar.
. Haga clic en *Administrar*.


Se produce un error en la operación cuando Microsoft SQL Server carece de ciertos módulos PowerShell y scripts de gestión. La fábrica de cargas de trabajo activa un trabajo de preparación de recursos para instalar los módulos y scripts que faltan, que puede ver en el separador Supervisión de trabajos. Cuando finalice el trabajo, vuelva a intentarlo para gestionar la instancia de host.



== Ver una instancia gestionada

Puede ver una instancia gestionada siguiendo estos pasos.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. En Bases de datos, seleccione la pestaña *Inventario*.
. Haga clic en la flecha desplegable para expandir la fila del host y ver sus instancias gestionadas.
+
El host se expande y aparecen las instancias del host.

. Haga clic en el menú de tres puntos de la instancia para ver y luego seleccione *Ver instancia*.


.Resultado
La visión general de la instancia aparece en el separador Inventario.



== Ver bases de datos

Puede ver las bases de datos gestionadas por la instancia gestionada siguiendo estos pasos.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. En Bases de datos, seleccione la pestaña *Inventario*.
. Haga clic en la flecha desplegable para expandir la fila del host para ver sus bases de datos.
+
El host se expande y aparecen las instancias del host.

. Haga clic en el menú de tres puntos de la instancia que contiene las bases de datos que desea ver.
. Seleccione *Ver bases de datos*.


.Resultado
La lista de bases de datos de la instancia aparece en la pestaña Inventory.



== Anular la gestión de una instancia de host

Anule la gestión de una instancia de host siguiendo estos pasos.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. En Bases de datos, seleccione la pestaña *Inventario*.
. Haga clic en la flecha desplegable para ampliar la fila de la instancia de host que desea anular la gestión.
+
El host se expande y aparecen las instancias del host.

. Haga clic en el menú de tres puntos de la instancia que desea desgestionar.
. Seleccione *Desgestionar*.


.Resultado
La instancia de host ahora no está gestionada.
