---
sidebar: sidebar 
permalink: manage-instance.html 
keywords: instance, instance management, FSx for ONTAP, instance, manage host, view host, database host, database instance, manage 
summary: Obtenga información sobre la administración de instancias y bases de datos en NetApp Workload Factory for Databases. 
---
= Gestión de recursos en NetApp Workload Factory para bases de datos
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La administración de recursos en NetApp Workload Factory for Databases le permite utilizar funciones avanzadas, incluida la creación de bases de datos y clones, la utilización de recursos y la supervisión. Además, puede analizar el estado de la arquitectura de sus configuraciones de base de datos e implementar las mejores prácticas de configuración para mejorar el rendimiento y reducir los costos operativos. La administración de recursos es solo para entornos Microsoft SQL Server y Oracle que se ejecutan en FSx para el almacenamiento del sistema de archivos ONTAP .

Usted debelink:register-instance.html["registrar recursos"] realizar cualquiera de las siguientes tareas de gestión.

Las tareas de gestión incluyen:

* Visualización de bases de datos desde el Inventario
* link:create-database.html["Creando una base de datos"]
* link:create-sandbox-clone.html["Creación de un clon de base de datos (sandbox)"]
* link:optimize-configurations.html["Implementación de configuraciones de bases de datos bien diseñadas"]

