---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: Workload Factory for Databases analiza periódicamente las configuraciones de Microsoft SQL Server y Oracle para determinar si hay algún problema. 
---
= Análisis de configuración para entornos de bases de datos en Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for Databases analiza periódicamente las configuraciones de las bases de datos para determinar si hay problemas con las implementaciones de Microsoft SQL Server y Oracle en Amazon FSx for NetApp ONTAP .  Cuando se detectan problemas, Workload Factory le muestra cuáles son y le explica qué debe cambiar para garantizar que las configuraciones de su base de datos alcancen el máximo rendimiento, rentabilidad y cumplimiento de las mejores prácticas.

Estas son algunas funcionalidades clave:

* Análisis diario de la configuración
* Validaciones automáticas de prácticas recomendadas
* Recomendaciones de tamaño correcto
* Capacidad de observación proactiva
* Información para la acción
* Asesor de buen diseño de marco de trabajo de AWS




== Componentes del análisis de configuración

El análisis de configuración incluye los siguientes componentes:

Estado bien diseñado:: El estado de buena arquitectura se refiere al estado general de las configuraciones de su base de datos; las configuraciones se clasifican como "optimizadas", "no optimizadas" o "con exceso de aprovisionamiento". El estado de una configuración bien diseñada se consulta desde una instancia de Microsoft SQL Server o una base de datos Oracle en la consola de Workload Factory.
Partitura bien diseñada:: La puntuación incluye todas las configuraciones analizadas actualmente y se muestra como un porcentaje. Una puntuación del 25% significa que el 25% de sus implementaciones de bases de datos están bien diseñadas. La puntuación de buena arquitectura se consulta desde la pantalla *Buena arquitectura* y desde una instancia de Microsoft SQL Server o una base de datos Oracle en la consola de Workload Factory.
Categorías de configuración:: Las configuraciones se organizan en las siguientes categorías: almacenamiento, computación, aplicación, resiliencia y clonación. Cada categoría incluye evaluaciones de configuración específicas que se analizan periódicamente. Las categorías de configuración se referencian desde la pantalla *Bien arquitectónico* y desde dentro de una instancia de Microsoft SQL Server o una base de datos Oracle en la consola de Workload Factory.




== Alcance del análisis

El alcance de la optimización es diferente dependiendo del componente que se esté evaluando. Por ejemplo, la optimización del almacenamiento se produce en el nivel de instancia de SQL mientras que la optimización de computación se produce en el nivel de host.



== Requisitos de análisis

Para un análisis completo del entorno de base de datos, los recursos deben estar registrados y en línea.

link:register-instance.html["Aprenda cómo registrar recursos."]

.El futuro
link:optimize-configurations.html["Implementar configuraciones de bases de datos bien diseñadas"]
