---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: Workload Factory para bases de datos escanea las configuraciones de Microsoft SQL Server y proporciona información y recomendaciones para ayudarle a lograr la excelencia operativa. 
---
= Implementar configuraciones de base de datos bien diseñadas en la fábrica de carga de trabajo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Con la información y las recomendaciones del análisis de configuración, aproveche Workload Factory para implementar las mejores prácticas para las configuraciones de su base de datos. Puede identificar fácilmente los problemas y tomar medidas para mejorar la arquitectura de cualquier configuración que no esté optimizada en términos de confiabilidad, seguridad, eficiencia, rendimiento y costo.

.Acerca de esta tarea
Workload Factory analiza diariamente las configuraciones de la base de datos. Este análisis diario proporciona información y recomendaciones, con opciones para corregir automáticamente los problemas de configuración y que estas cumplan con las mejores prácticas.

Tiene opciones para revisar las recomendaciones de problemas de configuración y solucionar esos problemas desde el inventario de Bases de datos dentro de la consola de fábrica de carga de trabajo.

Qué se analiza:: La fábrica de carga de trabajo analiza el estado de buena arquitectura de las siguientes configuraciones para instancias de Microsoft SQL Server:
+
--
* Ajuste de tamaño del almacenamiento: Incluye nivel de almacenamiento, margen adicional del sistema de archivos, tamaño de la unidad de registro y tamaño de la unidad TempDB
* Distribución de almacenamiento: Incluye la ubicación de los archivos de datos del usuario, la ubicación de los archivos de registro y la ubicación de TempDB
* Configuración de almacenamiento: incluye administración de capacidad, aprovisionamiento fino, política de niveles, instantáneas, estado de E/S de múltiples rutas de Microsoft (MPIO) y configuración de tiempo de espera de MPIO
* Informática: Incluye ajustes de tamaño, parches del sistema operativo y ajustes de adaptadores de red como escalado lateral de recepción (RSS) y descarga de TCP
* Aplicaciones: Incluye licencias de Microsoft SQL Server, parche de Microsoft SQL Server y configuración de MAXDOP
* Resiliencia: Incluye snapshots locales, FSx para backups de ONTAP y replicación entre regiones (CRR)
* Clones: incluye opciones para actualizar y eliminar clones (sandboxes) que se crearon dentro o fuera de la fábrica de carga de trabajo y que tienen más de 60 días


--


.Antes de empezar
* Debes tener link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Credenciales de la cuenta de AWS y permisos de lectura y escritura"^] para analizar las configuraciones de su base de datos.
* Para evaluar el almacenamiento de una instancia de Microsoft SQL Server, la instancia debe estar registrada en Workload Factory y el tipo de almacenamiento debe ser FSx para ONTAP. link:register-instance.html["Aprenda cómo registrar una instancia."]
* Asegúrese de revisar cada recomendación cuidadosamente antes de seleccionar para corregir una configuración o configuración. Para la configuración de RSS y MAXDOP, le sugerimos que pruebe la configuración recomendada para determinar las mejoras de rendimiento antes de realizar cambios en su entorno de producción.



NOTE: El proceso de corrección puede provocar tiempos de inactividad de instancias o interrupciones del servicio. Asegúrese de revisar la recomendación cuidadosamente antes de decidir arreglar una configuración.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. En la pestaña *Inventario*, seleccione la pestaña *Instancias*.
. Seleccione *Solucionar problemas* para ver los problemas de configuración de la instancia.
. En la página de estado Bien diseñado de la instancia, revise los hallazgos del análisis.
+
Puede filtrar problemas de configuración por categorías, subcategorías, estado, gravedad y etiquetas.

+
También puede descargar un informe de los hallazgos seleccionando *Exportar PDF*.

. Seleccione la flecha desplegable para ver la recomendación de cualquier configuración. Las recomendaciones incluyen las mejores prácticas, posibles riesgos de las configuraciones no optimizadas y consideraciones importantes. Asegúrese de revisar la recomendación cuidadosamente.
. Seleccione *Ver y corregir* problemas de configuración cuando la opción esté disponible.
+
*Seleccionar todo* es la opción predeterminada, pero puedes seleccionar recursos específicos para arreglarlos.

+
.. Para todas las configuraciones excepto la limpieza de clones, revise los detalles de la recomendación para saber qué sucederá si decide solucionar el problema. Algunas operaciones de remediación pueden causar tiempos de inactividad de las instancias o interrupciones del servicio.
.. Para la limpieza de clones, seleccione Bases de datos clonadas (sandboxes) que desea actualizar o eliminar.
+
*** Al actualizar un clon, este se sincroniza con su base de datos de origen. La actualización solo está disponible para los clones creados en fábrica de cargas de trabajo.
*** Eliminar un clon lo elimina de forma permanente, libera espacio de almacenamiento y reduce los costes. Puede eliminar clones creados dentro o fuera de la fábrica de cargas de trabajo.




. Seleccione *Continuar* para solucionar el problema de configuración.


.Resultado
La fábrica de carga de trabajo comienza a solucionar los problemas. Seleccione la pestaña *Supervisión de trabajos* para ver el estado de la operación.
