---
sidebar: sidebar 
permalink: protect-sql-server.html 
keywords: protect, server, Microsoft SQL Server, SQL Server, protect instance, protect database 
summary: Proteja las instancias y bases de datos de Microsoft SQL Server. 
---
= Proteger las cargas de trabajo de Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Proteja los datos de sus aplicaciones de Microsoft SQL Server utilizando NetApp Backup and Recovery desde la consola de Workload Factory. Con esta integración, puede lograr los siguientes objetivos de protección: realizar copias de seguridad de cargas de trabajo con instantáneas locales en el almacenamiento principal local de Amazon FSx for NetApp ONTAP (FSx for ONTAP) y replicar cargas de trabajo en el almacenamiento secundario de FSx para ONTAP .



== Acerca de esta tarea

Workload Factory automatiza el descubrimiento de recursos, la validación de requisitos previos y la configuración e instalación del complemento para Microsoft SQL Server a fin de prepararse para la protección de sus cargas de trabajo con NetApp Backup and Recovery. El complemento es un componente del lado del host del software NetApp que le permite proteger sus cargas de trabajo de Microsoft SQL Server.

NetApp Backup and Recovery aprovecha la tecnología de replicación de datos NetApp SnapMirror para garantizar que todas las copias de seguridad estén completamente sincronizadas mediante la creación de copias instantáneas y su transferencia a las ubicaciones de copia de seguridad.

Para obtener detalles sobre la protección con Backup and Recovery, consulte la link:https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-mssql-protect-overview.html["Proteja la descripción general de las cargas de trabajo de Microsoft SQL con Backup and Recovery"^].



== Antes de empezar

Se deben cumplir los siguientes requisitos para proteger las cargas de trabajo de Microsoft SQL Server con Backup and Recovery.

* Asegúrese de que su entorno cumpla link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-start-prereq.html#microsoft-sql-server-workload-requirements["Requisitos de copia de seguridad y recuperación de SQL Server"^].
* link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-start-prereq.html#in-netapp-console["Requisitos completos de la consola de NetApp"^] incluida la configuración, la asignación de roles de IAM y la instalación de un agente de consola.


Si tiene acceso de administrador de la organización a la cuenta de NetApp , `backup and recovery super admin` El rol se asigna automáticamente cuando usted<<Prepárese para la protección con NetApp Backup and Recovery,Prepárese para la protección con NetApp Backup and Recovery>> .

* Establezca la resolución del host en el conector
+
Para descubrir bases de datos, debe configurar la resolución del host en el Conector.  En el dispositivo alojado, agregue la asignación de la dirección IP al nombre de host en el `/etc/hosts` archivo.

+
** link:https://docs.netapp.com/us-en/data-services-backup-recovery/br-start-licensing.html["Configurar licencias para NetApp Backup and Recovery"^]






== Prepárese para la protección con NetApp Backup and Recovery

Complete el proceso de preparación para proteger sus recursos de Microsoft SQL Server con NetApp Backup and Recovery.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. Desde el menú Bases de datos, seleccione *Inventario*.
. En el Inventario, seleccione *Microsoft SQL Server* como tipo de motor.
. Localice la instancia que desea proteger y luego seleccione *Proteger* en el menú.
. Si se le solicita, proporcione credenciales de Windows con acceso administrativo.
+
Para utilizar NetApp Backup and Recovery para protección, las instancias de SQL Server deben estar registradas en Workload Factory con credenciales de Windows.

. Si hay varios agentes de consola activos y disponibles, seleccione el *Agente de consola* donde desea que se registre y proteja la carga de trabajo.
. Para prepararse para la protección de datos, Workload Factory registra automáticamente sus recursos de SQL Server en Backup and Recovery, configura e instala el complemento para Microsoft SQL Server y descubre recursos para cumplir con los requisitos previos para proteger su instancia de SQL Server. Seleccione *Iniciar* para comenzar el proceso.
. Después de cumplir con los requisitos previos, seleccione *Redirigir* para acceder a Copia de seguridad y recuperación.


.El futuro
Desde Copia de seguridad y recuperación, cree una política para proteger su instancia y bases de datos de Microsoft SQL Server.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-policies-create.html["Aprenda a crear una política para proteger su instancia y bases de datos de Microsoft SQL Server"^].

Para obtener información relacionada, consulte la link:https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-mssql-protect-overview.html["Documentación de copia de seguridad y recuperación"^] para administrar cargas de trabajo de Microsoft SQL Server.



== Protección de edición para recursos de Microsoft SQL Server

Puede editar la protección de las instancias y bases de datos de Microsoft SQL Server que ya están protegidas en NetApp Backup and Recovery. La edición de la protección le permite modificar la política o la programación de protección para sus instancias protegidas de SQL Server.

. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. Desde el menú Bases de datos, seleccione *Inventario*.
. En el Inventario, seleccione *Microsoft SQL Server* como tipo de motor.
. Seleccione la pestaña *Bases de datos*.
. Localice la base de datos cuya protección desea editar y, a continuación, seleccione *Editar protección* en el menú.
+
Se le redirigirá a Copia de seguridad y recuperación en la NetApp Console , donde podrá modificar la política de protección o la programación.


