---
sidebar: sidebar 
permalink: refresh-clone.html 
keywords: refresh clone, sync, update, database, Microsoft SQL 
summary: Actualice un clon de base de datos en NetApp Workload Factory for Databases para que sea equivalente a la base de datos de origen en el momento actual o en un punto anterior en el tiempo. 
---
= Actualizar un clon de base de datos en NetApp Workload Factory for Databases
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Actualice un clon de base de datos (sandbox) en NetApp Workload Factory for Databases para que sea equivalente a la base de datos de origen en el momento actual o en un punto anterior en el tiempo.

.Acerca de esta tarea
Actualizar un clon actualiza el clon en la base de datos de origen en el momento actual o en una copia de Snapshot de la base de datos de origen realizada en un momento específico anterior. Se eliminarán todos los cambios realizados en el clon del sandbox.

.Antes de empezar
La actualización sólo se puede realizar cuando la base de datos de origen está activa.

Para actualizar un clon de base de datos a partir de una instantánea, la base de datos de origen debe tener al menos una instantánea para la operación.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. Desde el menú Bases de datos, seleccione *Sandboxes*.
. En Sandboxes, seleccione el menú de acciones del clon del sandbox que desea actualizar.
. Selecciona *Refrescar*.
. En el cuadro de diálogo Refrescar, seleccione una de las siguientes opciones:
+
.. *Refrescar a la hora actual*
.. *Refrescar al punto en el tiempo*
+
Para esta opción, seleccione la instantánea de la base de datos en el menú desplegable a la que desea refrescar.



. Haga clic en *Actualizar*.

