---
sidebar: sidebar 
permalink: revert-clone.html 
keywords: re-baseline, revert clone, database, Microsoft SQL 
summary: Revierte un clon de espacio aislado en la fábrica de cargas de trabajo de BlueXP  para bases de datos. 
---
= Revierte un clon de espacio aislado en la fábrica de cargas de trabajo de BlueXP  para bases de datos
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Revierte un clon de base de datos a su versión original en el momento de la creación en la fábrica de cargas de trabajo de BlueXP  para bases de datos.

.Acerca de esta tarea
Cuando se clona una base de datos, el clon que se creó es un clon _baseline_. Los datos de la base de datos clonada son los mismos que los de la base de datos de origen en el momento de la creación. A medida que los datos del clon de una base de datos de un recuadro de pruebas cambian con el tiempo, tal vez desee revertir los datos de nuevo a la línea de base cuando el clon se creó por primera vez. Esta operación se denomina volver a establecer la base de referencia de un clon. Volver a establecer la base de referencia de un clon en lugar de crear un clon nuevo ahorra espacio; sin embargo, se eliminará cualquier cambio realizado al clon de sandbox.

.Pasos
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir a Inventario de Bases de Datos*.
. En las bases de datos, seleccione la pestaña *sandboxes*.
. En la pestaña sandboxes, haz clic en el menú de tres puntos del clon del sandbox que quieras revertir.
. Seleccione *Re-baseline*.
. En el cuadro de diálogo Volver a establecer la base, haga clic en *Volver a establecer la base*.

