---
sidebar: sidebar 
permalink: view-databases.html 
keywords:  
summary: Para obtener un resumen de los recursos de la base de datos en Workload Factory, consulte todas las bases de datos en el inventario. También puede ver las bases de datos por cada instancia registrada. 
---
= Ver bases de datos en la fábrica de carga de trabajo para bases de datos
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para obtener un resumen de los recursos de la base de datos en Workload Factory, consulte todas las bases de datos en el inventario. También puede ver las bases de datos por cada instancia registrada.

.Antes de empezar
* Las instancias de host que contienen recursos de base de datos deben tener FSx para el almacenamiento del sistema de archivos ONTAP.
* Las instancias de host deben estar registradas en la fábrica de carga de trabajo. Aprenda a link:register-instance.html["registrar instancias de host"].


.Pasos
[role="tabbed-block"]
====
.Ver bases de datos para una sola instancia
--
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. En Bases de datos, seleccione la pestaña *Inventario*.
. Haga clic en la flecha desplegable para expandir la fila del host para ver sus bases de datos.
+
El host se expande y aparecen las instancias del host.

. Haga clic en el menú de tres puntos de la instancia que contiene las bases de datos que desea ver.
. Seleccione *Ver bases de datos*.


--
.Ver bases de datos para todas las instancias
--
. Inicie sesión con uno de los link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiencias de consola"^]botones .
. En el mosaico Bases de datos, seleccione *Ir al inventario de bases de datos*.
. En Bases de datos, seleccione la pestaña *Inventario*.
. Haga clic en la flecha desplegable para expandir la fila del host para ver sus bases de datos.
+
El host se expande y aparecen las instancias del host.

. Haga clic en el menú de tres puntos de la instancia que contiene las bases de datos que desea ver.
. Seleccione *Ver bases de datos*.


--
====
.Resultado
Ha visto los recursos de la base de datos dentro de la fábrica de carga de trabajo.
