---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, databases, workload factory' 
summary: Descubra las novedades de Workload Factory para bases de datos. 
---
= Lo nuevo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra las novedades de las bases de datos.



== 4 de agosto de 2024



=== Mejoras en la calculadora de ahorro

* Descripciones de estimación de costes
+
Ahora puedes descubrir cómo se calculan las estimaciones de costes en la calculadora de ahorro. Podrás revisar las descripciones de todos los cálculos de tus instancias de Microsoft SQL Server con el almacenamiento Amazon Elastic Block Store en comparación con el uso de Amazon FSx para el almacenamiento de ONTAP.

* Soporte para el grupo de disponibilidad siempre disponible
+
Ahora las bases de datos proporcionan cálculos de ahorro de costes para el tipo de implementación de grupos de disponibilidad Always On con Microsoft SQL Server mediante Amazon Elastic Block Store.

* Optimiza las licencias de SQL Server con FSx para ONTAP
+
La calculadora de bases de datos determina si la edición de licencia de SQL que utiliza con el almacenamiento de Amazon Elastic Block Store está optimizada para las cargas de trabajo de base de datos. Obtendrás una recomendación sobre la licencia SQL óptima con el almacenamiento FSx para ONTAP.

* Varias instancias de SQL Server
+
Ahora las bases de datos proporcionan cálculos de ahorro de costes para una configuración que aloja varias instancias de Microsoft SQL Server mediante Amazon Elastic Block Store.

* Personalizar la configuración de la calculadora
+
Ahora puede personalizar la configuración de Microsoft SQL Server, Amazon EC2 y Elastic Block Store para explorar los ahorros manualmente. La calculadora de ahorro determinará la mejor configuración en función del coste.



link:explore-savings.html["Explora el ahorro con FSx para ONTAP para tus cargas de trabajo de base de datos."]



== 7 de julio de 2024



=== Lanzamiento inicial de Workload Factory para bases de datos

La versión inicial incluye la funcionalidad de explorar el ahorro con Amazon FSx para NetApp ONTAP como entorno de almacenamiento para tus cargas de trabajo de bases de datos, detectar, gestionar e implementar servidores de Microsoft SQL, implementar y clonar bases de datos, y supervisar estos trabajos en Workload Factory.

link:learn-databases.html["Obtenga más información sobre las bases de datos"].
