= Análisis de costes y planificación de migración de entornos de bases de datos on-premises SQL Server
:allow-uri-read: 




=== Análisis de costes y planificación de migración de entornos de bases de datos on-premises SQL Server

BlueXP Workload Factory para bases de datos ahora detecta, analiza y te ayuda a planificar la migración de bases de datos locales de SQL Server a Amazon FSx for NetApp ONTAP. Puedes usar la calculadora de ahorro para estimar el coste de ejecutar tu entorno de bases de datos locales de SQL Server en la nube y revisar recomendaciones para migrar tu entorno de bases de datos locales a la nube.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Explora el ahorro que puedes conseguir en entornos de bases de datos on-premises"]



=== Nuevas evaluaciones de optimización para bases de datos

Las siguientes evaluaciones ahora están disponibles en el fábrica de cargas de trabajo BlueXP  para bases de datos. Estas evaluaciones se centran en detectar y proteger contra posibles vulnerabilidades de seguridad, y en detectar y aliviar los cuellos de botella en el rendimiento.

* *Configuración de la escala lateral de recepción (RSS)*: Comprueba si la configuración RSS está habilitada y si el número de colas está establecido en el valor recomendado. La evaluación también proporciona recomendaciones para optimizar la configuración RSS.
* *Configuración del servidor de grado máximo de paralelismo (MAXDOP)*: La evaluación comprueba si MAXDOP está configurado correctamente y proporciona recomendaciones para optimizar el rendimiento.
* *Parches de Microsoft SQL Server*: La evaluación comprueba si los parches más recientes están instalados en las instancias de SQL Server y proporciona recomendaciones para instalar los parches más recientes.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimice las configuraciones"]
